name: Build EXE

on:
  push:
    branches:
      - main  # Ana branch'e yapılan her push'ta çalıştırılır

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile app.py

    - name: Upload EXE file
      uses: actions/upload-artifact@v2
      with:
        name: app-exe
        path: dist/app.exe
